# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-16 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170515_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='owing_since',
            field=models.DateTimeField(blank=True),
        ),
    ]
