# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-16 03:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170516_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='owing',
        ),
    ]
