# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-16 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170516_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_type',
            name='name',
            field=models.CharField(choices=[('Saque', 'Saque'), ('Depósito', 'Depósito'), ('Pagamento de Extrato', 'Pagamento de Extrato'), ('Juros sobre saldo negativo', 'Juros sobre saldo negativo'), ('Transferência bancária', 'Transferência bancária'), ('Pagamento de taxa de transferência bancária', 'Pagamento de taxa de transferência bancária'), ('Solicitação de visita do gerente', 'Solicitação de visita do gerente'), ('Recebimento de transferência bancária', 'Recebimento de transferência bancária')], max_length=50),
        ),
    ]
