# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-16 15:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20170516_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help_request',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
